@extends('layout.main')

@section('page_title')
    Terms and Conditions   
@stop

@section('inner_content')
    @include('section.default_heading', array('heading' => 'Terms and Conditions'))    
    
    <ol>
      <li>While every endeavour will be made to meet the wishes of Advertisers, the Publisher does not guarantee the insertion, the position, or the colour of any particular advertisement</li>
      <li>The Publisher does not accept responsibility for any loss or damage caused by (a) an error, inaccuracy or omission in the printing of the advertisement: (b) for any failure to publish an advertisement on the date or dates specified by the Advertiser: (c) for the publication of an advertisement on the date or dates specified by the Advertiser whether the actual date be earlier or later than the date or dates specified: and/or in respect of any loss or damage alleged to have arisen through delay in forwarding or omission to forward replies to Box Numbers to the Advertiser, however caused</li>
      <li>The Publisher reserves the right to omit, suspend, or change the position of any advertisement, even if it has already been accepted for publication.</li>
      <li>The Publisher reserves the right to make any alteration it considers necessary or desirable in an advertisement and to require artwork or copy to be amended to meet its approval.</li>
      <li>The Advertiser shall be responsible for checking an advertisement on each occasion that it is published. If the Company is shown to have made an error or inaccuracy in the insertion of or omission to insert any advertisement it shall make a refund or adjustment to the cost of the advertisement at a rate agreed between the Company and the Advertiser. No refund or adjustment will be made if the error or inaccuracy does not materially affect the cost or detract from the advertisement.</li>
      <li>Cancellation - The Publisher requires fourteen clear days notice in writing of cancellation, or reduction in the advertisement size, of any order or unexpired part of an order, or in the case of an advertisement which by reason of its position is chargeable at a premium rate, not less than twenty eight clear days notice before the insertion or the next insertion on payment of the difference (if any) between the rates for the series specified in the order and the usual price for the series of insertions which has appeared when the order is stopped.</li>
      <li>The Publisher reserves the right to require four clear days notice of cancellation of any order or unexpired part of an order, or in the case of an advertisement which by reason of its position is chargeable at a premium rate, not less than twenty-eight clear days notice before the insertion or the next insertion on payment of the difference (if any) between the rates for the series specified in the order and the usual price for the series of insertions which has appeared when the order is stopped.</li>
      <li>The Publisher reserves the right to increase advertisement rates at any time or to amend the terms of contract as regards space or frequency of insertion. In such event the Advertiser has the option of cancelling the balance of the contract without surcharge. If the Advertiser cancels the balance of a contract, except in the circumstances stated all unearned series discounts will be surcharged. The Publisher reserves the right of surcharge in the event of insertions not being completed within the contractual period.</li>
      <li>Credit accounts are strictly nett and unless by prior agreement will be pre-paid. Where credit agreement exists our terms are that our account must be settled within 28 days of the date of the advertisement. If the account is overdue, the Publisher reserves the right to suspend insertions.</li>
      <li>The Advertiser/Advertising Agency agrees to indemnify the Publisher in respect of all costs, damages, or other charges falling upon the newspaper as the result of legal actions or threatened legal actions arising from the publication of the advertisement, or any one or more of the series of advertisements, published in accordance with the copy instructions supplied to the newspaper in pursuance of the Advertiser's/Advertising Agency's order. In any case where a claim is made against the newspaper or the newspaper is used in litigation the Advertiser/Advertising Agency may ultimately be liable under the terms hereof, notice in writing shall be given to the Advertiser/Advertising Agency, and consultation shall take place before any expense is incurred or the claim is settled or the case is defended or otherwise disposed of.</li>
      <li>Copy must be supplied without application from the Publisher. In the event of copy instructions not being received by the copy date the Publisher reserves the right to repeat copy last used. The Publisher cannot accept changes in dates of insertion unless these are confirmed in writing in time for the change to be made. The Publisher reserves the right to charge for any additional expense involved in such changes.</li>
      <li>The placing of an order for the insertion of an advertisement shall amount to an acceptance of the above conditions and any conditions stipulated on an Agency's order form or elsewhere by an Agency or an Advertiser shall be void insofar as they are in conflict with them.</li>
      <li>Lineage advertisements must be pre-paid and refunds on cancellation are not given</li>
      <li>The Business Advertisement (Disclosure) requires all advertisements by people who seek to sell goods, in the course of a business, to make that fact clear. It is the responsibility of the advertiser to comply with the above Order by using the word TRADE or Capital 'T'.</li>
      <li>Marriage and Engagement Notices must be authorised in writing by both parties to the Engagement or Marriage.</li>
      <li>eshtihar.com reserves the right to publish advertisements in any of it's other publications.</li>
      <li>Refunds cannot be given on cancellations of advertisements which have already been published in any of our publications or on our Internet Web site.</li>
      <li>Please note that telephone calls to and from eshtihar.com are monitored and recorded. Recordings may be accessed for training, security and dispute resolution purposes.</li>
    </ol>   
@stop